### ISSUE TITLE
Error segunda linea

### ISSUE THREAD

**Issue by LautaroRomero21** [pdepmartestm/bienvenida-2023-ivansxs23#1]
Hola daniel en la segunda linea que dice "algunos datos sobre mi" pusiste un # en el principio. Nose si tu intencion era poner esa frase como subtitulo (en ese caso en el codigo debias poner "## Algunos datos sobre mi:") o simplemente lo pusiste sin querer.

**Comment by ivansxs23** [comment]
Ahí lo corregí muchas gracias
