### ISSUE TITLE
Tamaño de la imagen y errores de sintaxis

### ISSUE THREAD

**Issue by MateoPereyra88** [pdepmartestm/bienvenida-2023-ivansxs23#3]
Te recomiendo que achiques la imagen para que la presentación se vea mas linda. Acá te dejo el código:
\<img src="foto.jpg" width=20%>

Las listas y los encabezados deben tener un espacio antes del texto, ejemplos:

\# texto

\- elemento 1
\- elemento 2
\- elemento 3

**Comment by ivansxs23** [comment]
Listo ahi lo pude agregar, gracias por el consejo
